import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProveedorTrivia } from "../context/TriviaContext";
import PuntajeHeader from "../components/PuntajeHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutTrivia({ children }: any) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProveedorTrivia>
          <PuntajeHeader />
          <div className="max-w-xl mx-auto p-6 bg-white rounded shadow mt-8 text-center">
            {children}
          </div>
        </ProveedorTrivia>
      </body>
    </html>
  );
}
